source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

link_with 'kuafu', 'kuafuTests'

pod 'FMDB', :git => 'https://github.com/robertmryan/fmdb.git'
pod 'SnapKit', '~> 0.12.0'
pod 'MGSwipeTableCell', '~> 1.4.3'
pod 'CVCalendarKit', '~> 0.1.1'
pod 'JTCalendar', '~> 1.2.3'
pod 'MKEventKit', '~> 0.2.0'
pod 'JKRichTextView'
pod 'DAAlertController', '~> 0.1.4'
pod 'NJKWebViewProgress'

use_frameworks!

